//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace DataLayer
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;
    using System.Data.Entity;

	public static class DataManager
	{
        private static DBScoresContainer _context;
        private static ScoresRepository _scoresRepository;

		public static ScoresRepository ScoresRepository
		{
            get 
            {
                if (_scoresRepository == null)
                {
                    _scoresRepository = new ScoresRepository(_context);
                }
                return _scoresRepository;
            }
		}

		static DataManager()
		{
            _context = new DBScoresContainer();
            _context.ScoresSet.Load();
		}

	}
}

