//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace GameLogic
{
    using DataLayer;
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;

	public class Gamer
	{
        private static Gamer _instance;

        public static Gamer Instance
        {
            get
            {
                if (_instance == null)
                {
                    _instance = new Gamer();
                }
                return _instance;
            }
        }

		public virtual int Points
		{
			get;
			set;
		}

		public virtual int ShotNum
		{
			get;
			set;
		}

        private Gun Gun;

        private Gamer()
        {
            Gun = new Gun();
        }

        public virtual void StartGame()
        {
            ShotNum = 0;
            Points = 0;
            Gun.ResetKillPosition();
        }

		public virtual void RollDryer()
		{
            Gun.DoRollDryer();
		}

		public virtual bool Shot()
		{
            var result = Gun.DoShot();
            ShotNum++;
            if (!result)
            {
                this.AddPoints();
            }
            return result;
		}

		public virtual bool SavePoints(string name)
		{
            return DataManager.ScoresRepository.AddScores(name, Points);
		}

		private void AddPoints()
		{
            Points += 100;
            if (ShotNum >= 3)
            {
                Random r = new Random();
                int increaseNum = r.Next(2, 5);
                Points *= increaseNum;
            }
        }

        public virtual List<Scores> ShowScores()
		{
            return DataManager.ScoresRepository.List;
		}

	}
}

