//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace GameLogic
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Gun
	{
        private bool KillPosition;
        private int KillPositionNum;

        public virtual bool DoShot()
		{
            return KillPosition;
		}

        public virtual void DoRollDryer()
        {
            Random r = new Random();
            var rollResult = r.Next(1, 6);
            KillPosition = rollResult == KillPositionNum;
        }

        public Gun()
        {
            ResetKillPosition();
        }

        public virtual void ResetKillPosition()
        {
            Random r = new Random();
            KillPositionNum = r.Next(1, 6);
        }
	}
}

